services:
  studybot:
    image: dwipok/studybot:latest
    restart: unless-stopped
    container_name: studybot-container
    environment:
      - API_TOKEN=
      - SQL_HOST=
      - SQL_USER=postgres
      - SQL_PORT=5432
      - SQL_DATABASE=studybot
      - SQL_PASSWORD=
      - REDIS_HOST=
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - OPENAI_API=
      - WOLFRAM_API=
      - DEEP_TRANSLATE_API=
      - UCHUS_COOKIES=
  db:
    image: postgres:17.0
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: dwip312
      POSTGRES_USER: sasha
      POSTGRES_DB: studybot
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"