name: Create Release

on:
  push:
    branches:
      - release  # Change this to your specific branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Set up Node.js (if needed)
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '16' # Specify the Node.js version if your project needs it

    # - name: Install dependencies
    #   run: npm install  # Adjust this command based on your project

    # - name: Build project
    #   run: npm run build  # Replace with your build command

    - name: Create ZIP Archive
      run: |
        mkdir -p release
        zip -r release/docker-compose.zip docker-compose.yml sql_init-db/

    - name: Determine Release Version
      id: get_version
      run: echo "RELEASE_VERSION=v1.0.$(date +%s)" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: Release ${{ env.RELEASE_VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/docker-compose.zip
        asset_name: docker-compose.zip
        asset_content_type: application/zip
